version: '3.2'

services:
  api:
    build:
        context: .
        dockerfile: ./etc/dev/node/Dockerfile
    command:
      - "npm"
      - "start"
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=node
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: